### ISSUE TITLE
do you drive pager alerting via Alerta?

### ISSUE THREAD

**Issue by blysik** [guardian/alerta#107]
Is there a way to send email based alerting off of alerts?  I don't see any plugins for it, and wonder how you guys use this to drive an Ops team.

**Comment by satterly** [comment]
In the past we've had a dedicated [emailer component](https://github.com/guardian/alerta/tree/release/3.1/alerta/mailer) that listens to alerts on the RabbitMQ queue and sends emails.

However, most recently we've just integrated Alerta directly with [PagerDuty](https://github.com/alerta/alerta-contrib/tree/master/plugins/pagerduty) to give users more control over how, and when, they want to be notified (ie. via email or some other method). Note that when integrating with PagerDuty you can configure [web hooks](https://github.com/guardian/alerta/blob/master/alerta/app/webhooks/views.py#L241) so that Alerta is updated any time a change is made in PagerDuty.

**Comment by satterly** [comment]
There is now a contributed alert mailer. It is not fully featured but could be enhanced depending on needs. See https://github.com/alerta/alerta-contrib/tree/master/integrations/mailer
