### ISSUE TITLE
[question] what is top10?

### ISSUE THREAD

**Issue by blysik** [guardian/alerta#113]
Trying to figure out what search top10 is supposed to return? 

I have a current alert with a warning status, but top10 returns an empty list.

**Comment by satterly** [comment]
The search box in the Top10 page simply filters the results.

**Example** - search for "foo" in a list of 10 results shows 3 of those results with "foo" in either the resource or service name

<img width="854" alt="screen shot 2015-09-08 at 21 42 36" src="https://cloud.githubusercontent.com/assets/615057/9746906/8d2f242e-5672-11e5-8f0d-589754ac4665.png">

**Comment by blysik** [comment]
Sorry, I meant the top10 completely.  top10 by itself is a listing of some subset of current alerts.  I'm trying to figure out what that is.

**Comment by satterly** [comment]
Top10 is not a subset, it's all alerts but grouped first by count and then by duplicate count. It's meant to highlight alert sources that generate the most alerts so that you can address them if necessary. So in the above example, you can see that event "1221wsws" has generated 5 individual alerts for 5 different resources and 24 duplicates overall.

I find Top 10 useful when receiving a lot of syslog messages that turn out to be spam. I can quickly identify the worst offenders and modify the syslog parser to reject or reduce those alerts.
