### ISSUE TITLE
Mixed content error while accessing alerta 

### ISSUE THREAD

**Issue by unaisarakkal** [guardian/alerta#120]
I am getting a mixed content error - Blocked loading mixed active content "http://alerta.mydomain.com:8080/alerts/count?status=open"

http://alerta.mydomain.com is already redirected (301) to https://alerta.mydomain.com and working

The error is same with default config (ie. removed /etc/alerta.conf) and with alerta.conf. Also tried with both environments development and production

Anyhow my config is as follows:-

[DEFAULT]
timezone = India
output = json

[profile production]
endpoint = https://alerta.mydomain.com
key = demo-key

[profile development]
endpoint = https://alerta.mydomain.com:8080
debug = yes

DEBUG = False

SECRET_KEY = r'0Afk\(,8$cr(Y8:MA""knd>[@$U[G.eQL6DjAmVs'

QUERY_LIMIT = 10000  # maximum number of alerts returned by a single query
HISTORY_LIMIT = 100  #

# MongoDB
MONGO_HOST = 'localhost'
MONGO_PORT = 27017
MONGO_DATABASE = 'monitoring'
MONGO_REPLSET = None  # 'alerta'

MONGO_USERNAME = 'alerta'
MONGO_PASSWORD = None

AUTH_REQUIRED = False
OAUTH2_CLIENT_ID = 'INSERT-OAUTH2-CLIENT-ID-HERE'  # Google or GitHub OAuth2 client ID and secret
OAUTH2_CLIENT_SECRET = 'INSERT-OAUTH2-CLIENT-SECRET-HERE'
ALLOWED_EMAIL_DOMAINS = ['gmail.com']
ALLOWED_GITHUB_ORGS = ['guardian']
API_KEY_EXPIRE_DAYS = 365  # 1 year

CORS_ALLOW_HEADERS = ['Content-Type', 'Authorization', 'Access-Control-Allow-Origin']
CORS_ORIGINS = [
    'https://alerta.mydomain.com',
    'chrome-extension://jplkjnjaegjgacpfafdopnpnhmobhlaf',
    'https://localhost'
]
CORS_SUPPORTS_CREDENTIALS = AUTH_REQUIRED

BLACKOUT_DURATION = 3600  # default period = 1 hour

**Comment by satterly** [comment]
Make sure the API and the web console are **both** on HTTPS if you have decided to use SSL encryption. You're getting a "mixed content" error because some requests are being made to HTTP not HTTPS endpoints.

Alerta definitely works on HTTPS if configured properly. There is an example running on [Heroku](https://alerta.herokuapp.com/#/alerts?status=open) that uses HTTPS.

Note: `alerta.conf` is the config file for the `alerta` command-line tool and it is an INI-file format. `alertad.conf` is the config file for the `alertad` server and is just a plain python file.

**Comment by satterly** [comment]
If you're still having problems join me on Gitter for IRC chat https://gitter.im/alerta/chat

**Comment by satterly** [comment]
Solved. It was an nginx config problem. For future reference, see [here](https://github.com/alerta/docker-alerta/blob/master/nginx.conf) for an example working config.
