### ISSUE TITLE
Alerts on heartbeat - Feature request

### ISSUE THREAD

**Issue by priyadarsh** [guardian/alerta#126]
The heart beat api in alerta is quite interesting where applications push the status to alerta. But one thing missing is the alerts on heart beats when a particular heart beat becomes stale.

**Comment by satterly** [comment]
Someone asked a similar question a few months ago. See https://github.com/guardian/alerta/issues/110#issuecomment-137274985 -- I'll add something to the online docs.

**Comment by priyadarsh** [comment]
I found this after raising this request. Moving this to proper location in documentation might help.
http://docs.alerta.io/en/latest/deployment.html#house-keeping

**Comment by satterly** [comment]
alerta/alerta-docs@a5662b42da528c73bbe8b5b568be9f7df9b42fa5 and alerta/alerta-docs@5231b4851e6a1a54c5033a9c6ee7accabdc5b057

**Comment by msupino** [comment]
This doesnt seem to work, i have a heartbeat which should show an alert , but it doesnt, 

/usr/local/bin/alerta heartbeats --alert
ORIGIN                       TAGS                       CREATED              LATENCY TIMEOUT SINCE             STATUS

<img width="1048" alt="screenshot 2016-07-03 10 28 22" src="https://cloud.githubusercontent.com/assets/2325397/16544285/06de7f50-4109-11e6-9a88-3481ee566587.png">

**Comment by msupino** [comment]
sorry, my bad, this needs a api key not attached to company

**Comment by satterly** [comment]
@msupino No problem. Glad you worked it out.
