### ISSUE TITLE
"Services" seems to be a required field as well

### ISSUE THREAD

**Issue by madshall** [guardian/alerta#148]
When I post data using API I'm getting 403 `"[POLICY] Alert must define a service"` so I assume this fields is a required one as well as `resource` and `event ` are.

**Comment by satterly** [comment]
Only `resource` and `event` are mandatory fields. You are getting this response because the `reject` policy plugin is enabled in the default configuration. If you want to allow systems/users to submit new alerts without a `service` or with an `environment` different to either `Production` or `Development` then modify or disable this plugin. See this [previous issue](https://github.com/guardian/alerta/issues/106#issuecomment-124728745) explaining how.
