### ISSUE TITLE
Raise severities for cloudwatch alarms

### ISSUE THREAD

**Issue by tdi** [guardian/alerta#175]
Cloudwatch has only two severities: `OK` and `ALARM` plu one informative `INSUFFICIENT_DATA`. Since `ALARM` is the highest severity I would raise it to `critical`, `INSUFFICIENT_DATA` to `major` and OK leave as `normal`. 

The rationale by this is that  since ALARM is used for alarms, it should have the highest priority. 

This can be done either statically, just as now or by supplying severty map in config. I can as always provide a PR for both.

**Comment by satterly** [comment]
This is a good use case for a [plugin](https://github.com/alerta/alerta-contrib/tree/master/plugins) because not everyone would agree with your choice of severity levels.

It would be great if you could write a plugin to make the severities configurable for AWS cloudwatch. You could call it `alerta-cloudwatch` plugin and we could add it to the alerta-contrib repo.

It would look something like ...

```
class AwsCloudwatch(PluginBase):

    def pre_receive(self, alert):
        if alert.event_type != 'cloudwatchAlarm':
            return alert
        if alert.raw_data['NewStateValue'] == 'ALARM':
            severity = 'critical'
        else ...
```

What do you think?

**Comment by tdi** [comment]
This is a good idea. I will take this path.

**Comment by tdi** [comment]
I will close this one. We have creaed a plugin and will PR  to alerta-contrib

**Comment by satterly** [comment]
Thanks.
