### ISSUE TITLE
Warn users if they try to create API keys when auth is not enabled

### ISSUE THREAD

**Issue by satterly** [guardian/alerta#206]
It is not necessary to create API keys if authentication is not enabled. The web UI and CLI tool should make this more obvious by either not displaying the API key web view or returning a useful error to the user if `AUTH_REQUIRED` = `False`.

**Comment by satterly** [comment]
A different approach has been taken here to let users create new API keys even if authentication is not enabled but provide a better error message if they try to do so with have the proper credentials or supplying the correct request parameters.

**Comment by bhkumar** [comment]
Hi,

I am not able to integrate prometheus with alerta.io because I need to create API keys here and also I am not able to login with the admin role so please suggest to me and guide me what to do for this.
![Capture](https://user-images.githubusercontent.com/20926912/86960330-f9d7db00-c17c-11ea-8bbf-c2f8ab3a5a68.JPG)

**Comment by satterly** [comment]
Don't post new comments to the bottom of closed issues that are unrelated to your issue. If you need help to do something ask on [Gitter chat](https://gitter.im/alerta/chat). Thanks.
