### ISSUE TITLE
Prometheus Webhook and Timestamps w/ UTC offset

### ISSUE THREAD

**Issue by zachmoody** [guardian/alerta#280]
Really cool project you have going here. I've noticed some strange behavior though with the prometheus webhook and the amqp/mailer integration. Seems that new alerts get their `createTime` attribute's milliseconds field moved to the UTC offset.

e.g. `2016-11-12T17:37:02.804-05:00` gets turned into `2016-11-12T17:37:02-05:00.804Z`

This causes an exception in `parse_alert()` when mailer.py consumes the alert from the message queue.

I think I've narrowed it down to how the iso timestamp is being formed in https://github.com/guardian/alerta/blob/master/alerta/app/alert.py#L113 (and L282). Telling `replace()` to zero out the tzinfo leaves a timestamp that `parse_alert()` doesn't complain about, but I'm not sure that's the best way to solve it. Happy to submit a PR with those changes or any other ideas you might have though. Thanks!

**Comment by satterly** [comment]
Hi, I suspect the problem is [here](https://github.com/guardian/alerta/blob/master/alerta/app/webhooks/views.py#L298) where the original prometheus alert `startsAt` date is parsed. I had to put [something special](https://github.com/guardian/alerta/pull/147) in place for that and maybe something has changed or there was an edge case I wasn't aware of.

What would be really useful is if you could include in this issue some example raw prometheus alert notifications so we can compare with what is [currently being used](https://github.com/guardian/alerta/blob/master/tests/test_webhooks.py) in tests.

**Comment by zachmoody** [comment]
Perfect, thanks @satterly!

**Comment by satterly** [comment]
@zachmoody You're welcome. Thanks for reporting it. Available now as Alerta sever version 4.8.11.
