### ISSUE TITLE
API Keys that starts from / cant be deleted

### ISSUE THREAD

**Issue by freeseacher** [guardian/alerta#342]
Accidentally api key that starts from / was created. 
it can't be revoked via webiface 
https://XXX/api/key//ZQENk3/Dur3jAlPDtckAvJKRP53FpknhDdoLqIZ
GOT 
<title>405 Method Not Allowed</title>

**Comment by satterly** [comment]
That's not good. What if you try the url encoded value for slash. %2F ?

**Comment by freeseacher** [comment]
i've already delete that key from mongodb. sorry :(

**Comment by satterly** [comment]
Not sure how this could have happened in the first place because the API key generator function [create_key()](https://github.com/guardian/alerta/blob/master/alerta/app/database/mongo.py#L1415) uses [urlsafe_b64encode](https://docs.python.org/2/library/base64.html#base64.urlsafe_b64encode) which substitutes `_` for `/`.
