### ISSUE TITLE
Ability to set default timeout in the alerta configuration file

### ISSUE THREAD

**Issue by m4ce** [guardian/alerta#382]
Any chance one can set the DEFAULT_TIMEOUT option in the global settings? I'd want to avoid overriding the default for each and every alert all the time. It would be nice if I could override it centrally once and for all.

**Comment by satterly** [comment]
Not easily with the current version of Alerta because of circular imports of the config settings. This will be fixed in the next major release.

In the meantime, you can use [this](https://github.com/alerta/alerta-contrib/tree/master/plugins/timeout) plugin which sets a global timeout on alerts as they are received.

**Comment by m4ce** [comment]
Thank you!
