### ISSUE TITLE
timeout must be an integer

### ISSUE THREAD

**Issue by thehilll** [guardian/alerta#406]
Not sure this is something to fix, but we send some alerts via curl from some hosts where we have been unable to get the cli tool installed (Solaris mainly), and we've run into an error on v5 server that seems similar to an issue we reported for the client [https://github.com/alerta/python-alerta-client/issues/85](here).

However, I don't see how this could be the client b/c we are sending it in w/curl:

```
/usr/bin/curl -s -XPOST https://alerta-api.host.com/alert -H 'Authorization: Key xxx' -H 'Content-type: application/json' -d @/tmp/file.json
{
  "code": 400,
  "errors": null,
  "message": "timeout must be an integer",
  "status": "error"
}
```

When this json includes `"timeout": "108000"` the above fails, but when we write it as `"timeout": 108000` and use an actual integer it works fine.  Either worked on v4.

On the client this was a real issue b/c even an integer would fail.  Here it is more an annoyance to anyone (incorrectly) sending an integer as a string to a v4 server.

**Comment by satterly** [comment]
I had to be more strict in what input I allowed with v5 because it has to work will both MongoDB and Postgres and with Postgres you need to define column types for tables. So yes, it's an annoyance that things have gotten more strict but is it not easily fixed by using a the proper type for a timeout in the curl POST data?

**Comment by thehilll** [comment]
It's trivial to fix, so if there's a reason to leave it I would.
